// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace VdarApi.Migrations
{
    [DbContext(typeof(VdarDbContext))]
    [Migration("20190323084718_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.ConfirmationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<DateTime>("ExpireDateUTC");

                    b.Property<string>("HashCode");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("KeyType")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationKeys");
                });

            modelBuilder.Entity("Entities.Models.Tokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired();

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("FingerPrint")
                        .IsRequired();

                    b.Property<string>("IP");

                    b.Property<DateTime>("LastRefreshDateUTC");

                    b.Property<string>("Location");

                    b.Property<string>("RefreshToken")
                        .IsRequired();

                    b.Property<string>("UpdateHashSum")
                        .IsRequired();

                    b.Property<string>("UserAgent");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActivatedDateUtc");

                    b.Property<DateTime?>("Birthday");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailIsConfirmed");

                    b.Property<string>("FathersName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<bool>("PhoneIsConfirmed");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Salt");

                    b.Property<string>("SurName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, ActivatedDateUtc = new DateTime(2019, 3, 9, 8, 3, 5, 861, DateTimeKind.Utc), Birthday = new DateTime(1992, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatedDateUtc = new DateTime(2019, 3, 23, 8, 47, 17, 862, DateTimeKind.Utc), Email = "admin@google.com", EmailIsConfirmed = false, FathersName = "Andreevich", IsActive = true, Login = "vektor", Name = "Viktor", Password = "NNItlsZ4AqDhTbvfp34fZ3uBbha4KfPxwHjl1gJob4A=", PhoneIsConfirmed = true, PhoneNumber = "7771291221", Salt = "lrg2WHC1g9+fOjqIFKFHRw==", SurName = "Bochikalov" },
                        new { Id = 2, CreatedDateUtc = new DateTime(2019, 3, 23, 8, 47, 17, 864, DateTimeKind.Utc), EmailIsConfirmed = false, IsActive = true, Name = "Levon", Password = "dNYtoT6mDNWqiJMr4MhH0WFfxCGb/uNXC1e6eFECp2k=", PhoneIsConfirmed = false, PhoneNumber = "7771940504", Salt = "0EDX042sj+8KZwWJuFGxJg==", SurName = "Kukuyan" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
