// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace VdarApi.Migrations
{
    [DbContext(typeof(VdarDbContext))]
    [Migration("20190521104834_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Ads", b =>
                {
                    b.Property<int>("AdsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentUrl");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Message");

                    b.Property<int>("OwnerId");

                    b.Property<int>("QuantityViews");

                    b.HasKey("AdsId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ads","Action");
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities","Info");

                    b.HasData(
                        new { CityId = 1, CountryId = 1, Name = "Алматы" },
                        new { CityId = 2, CountryId = 1, Name = "Нур-Султан" },
                        new { CityId = 3, CountryId = 1, Name = "Караганда" },
                        new { CityId = 4, CountryId = 1, Name = "Кызылорда" },
                        new { CityId = 5, CountryId = 1, Name = "Тараз" },
                        new { CityId = 6, CountryId = 1, Name = "Семипалатинск" },
                        new { CityId = 7, CountryId = 1, Name = "Павлодар" }
                    );
                });

            modelBuilder.Entity("Entities.Models.ConfirmationKey", b =>
                {
                    b.Property<int>("ConfirmationKeyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<DateTime>("ExpireDateUTC");

                    b.Property<string>("HashCode");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("UserId");

                    b.HasKey("ConfirmationKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmationKeys","Identity");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("CountryId");

                    b.ToTable("Countries","Info");

                    b.HasData(
                        new { CountryId = 1, Name = "Казахстан" }
                    );
                });

            modelBuilder.Entity("Entities.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutCompanyHTML");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactMobile");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastActivity");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("Sault");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners","Action");
                });

            modelBuilder.Entity("Entities.Models.SocialNetwork", b =>
                {
                    b.Property<int>("SocialNetworkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<int>("OwnerId");

                    b.Property<int>("Type");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("SocialNetworkId");

                    b.HasIndex("OwnerId");

                    b.ToTable("SocialNetworks","Action");
                });

            modelBuilder.Entity("Entities.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDateUTC");

                    b.Property<int>("LimiteQuantityMember");

                    b.Property<int>("QuantityMember");

                    b.Property<DateTime>("StartDateUTC");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .HasMaxLength(500);

                    b.Property<int>("Type");

                    b.HasKey("StockId");

                    b.ToTable("Stocks","Action");
                });

            modelBuilder.Entity("Entities.Models.StockDetail", b =>
                {
                    b.Property<int>("StockDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdsId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MessageHTML");

                    b.Property<int>("QuantityViews");

                    b.Property<int>("Rate");

                    b.Property<int>("StockId");

                    b.HasKey("StockDetailId");

                    b.HasIndex("AdsId");

                    b.HasIndex("StockId");

                    b.ToTable("StockDetails","Action");
                });

            modelBuilder.Entity("Entities.Models.StockView", b =>
                {
                    b.Property<int>("StockViewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEndUTC");

                    b.Property<DateTime>("DateStartUTC");

                    b.Property<int>("Status");

                    b.Property<int>("StockDetailId");

                    b.Property<int>("UserId");

                    b.HasKey("StockViewId");

                    b.HasIndex("StockDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("StockViews","Action");
                });

            modelBuilder.Entity("Entities.Models.StockViewConfirm", b =>
                {
                    b.Property<int>("StockViewConfirmId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateClickConfirmUTC");

                    b.Property<DateTime>("DateShowConfirmUTC");

                    b.Property<int>("StockViewId");

                    b.HasKey("StockViewConfirmId");

                    b.HasIndex("StockViewId");

                    b.ToTable("StockViewConfirms","Action");
                });

            modelBuilder.Entity("Entities.Models.StockViewDetail", b =>
                {
                    b.Property<int>("StockViewDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFixationUTC");

                    b.Property<int>("StockViewId");

                    b.Property<int>("TimeLine");

                    b.HasKey("StockViewDetailId");

                    b.HasIndex("StockViewId");

                    b.ToTable("StockViewDetails","Action");
                });

            modelBuilder.Entity("Entities.Models.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("FingerPrint")
                        .IsRequired();

                    b.Property<string>("IP")
                        .HasMaxLength(100);

                    b.Property<DateTime>("LastRefreshDateUTC");

                    b.Property<string>("Location");

                    b.Property<string>("RefreshToken")
                        .IsRequired();

                    b.Property<string>("UpdateHashSum")
                        .IsRequired();

                    b.Property<string>("UserAgent");

                    b.Property<int>("UserId");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens","Identity");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActivatedDateUtc");

                    b.Property<DateTime?>("Birthday");

                    b.Property<int?>("CityId");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<string>("Email")
                        .HasMaxLength(320);

                    b.Property<bool>("EmailIsConfirmed");

                    b.Property<bool>("EmailIsSubscribe");

                    b.Property<string>("EmailKeyUnSubscribe");

                    b.Property<string>("FathersName")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Login")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("PhoneIsConfirmed");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Salt")
                        .HasMaxLength(50);

                    b.Property<string>("SurName")
                        .HasMaxLength(250);

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.ToTable("Users","Identity");

                    b.HasData(
                        new { UserId = 1, ActivatedDateUtc = new DateTime(2019, 5, 7, 10, 4, 22, 278, DateTimeKind.Utc), Birthday = new DateTime(1992, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), CityId = 1, CreatedDateUtc = new DateTime(2019, 5, 21, 10, 48, 34, 279, DateTimeKind.Utc), Email = "admin@google.com", EmailIsConfirmed = false, EmailIsSubscribe = false, FathersName = "Andreevich", IsActive = true, Login = "vektor", Name = "Viktor", Password = "IEF42EQpZswVSldQapwVnv6U4z8BoEvysfXSdUto6d0=", PhoneIsConfirmed = true, PhoneNumber = "7771291221", Salt = "Xvot2f0+bUcAjyRkWKdwmQ==", SurName = "Bochikalov" },
                        new { UserId = 2, CityId = 1, CreatedDateUtc = new DateTime(2019, 5, 21, 10, 48, 34, 281, DateTimeKind.Utc), EmailIsConfirmed = false, EmailIsSubscribe = false, IsActive = true, Name = "Levon", Password = "yT9q/QmEkRh/qnG9Qn3sLjRhNnmRTWhe/tdkuAXyn08=", PhoneIsConfirmed = false, PhoneNumber = "7771940504", Salt = "K9kgjCuNehdq6BNv+G5obg==", SurName = "Kukuyan" }
                    );
                });

            modelBuilder.Entity("Entities.Models.Winner", b =>
                {
                    b.Property<int>("WinnerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Place");

                    b.Property<int>("StockId");

                    b.Property<int>("UserId");

                    b.HasKey("WinnerId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("Winners","Action");
                });

            modelBuilder.Entity("Entities.Models.Ads", b =>
                {
                    b.HasOne("Entities.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.ConfirmationKey", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("ConfirmationKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.SocialNetwork", b =>
                {
                    b.HasOne("Entities.Models.Owner", "Owner")
                        .WithMany("SocialNetworksList")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.StockDetail", b =>
                {
                    b.HasOne("Entities.Models.Ads", "Ads")
                        .WithMany()
                        .HasForeignKey("AdsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.StockView", b =>
                {
                    b.HasOne("Entities.Models.StockDetail", "StockDetail")
                        .WithMany()
                        .HasForeignKey("StockDetailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.StockViewConfirm", b =>
                {
                    b.HasOne("Entities.Models.StockView", "StockView")
                        .WithMany()
                        .HasForeignKey("StockViewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.StockViewDetail", b =>
                {
                    b.HasOne("Entities.Models.StockView", "StockView")
                        .WithMany()
                        .HasForeignKey("StockViewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Token", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Entities.Models.Winner", b =>
                {
                    b.HasOne("Entities.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
