// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace VdarApi.Migrations
{
    [DbContext(typeof(VdarDbContext))]
    [Migration("20190410095849_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.ConfirmationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<DateTime>("ExpireDateUTC");

                    b.Property<string>("HashCode");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmationKeys");
                });

            modelBuilder.Entity("Entities.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("FingerPrint")
                        .IsRequired();

                    b.Property<string>("IP")
                        .HasMaxLength(100);

                    b.Property<DateTime>("LastRefreshDateUTC");

                    b.Property<string>("Location");

                    b.Property<string>("RefreshToken")
                        .IsRequired();

                    b.Property<string>("UpdateHashSum")
                        .IsRequired();

                    b.Property<string>("UserAgent");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActivatedDateUtc");

                    b.Property<DateTime?>("Birthday");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<string>("Email")
                        .HasMaxLength(320);

                    b.Property<bool>("EmailIsConfirmed");

                    b.Property<bool>("EmailIsSubscribe");

                    b.Property<string>("EmailKeyUnSubscribe");

                    b.Property<string>("FathersName")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Login")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("PhoneIsConfirmed");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Salt")
                        .HasMaxLength(50);

                    b.Property<string>("SurName")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, ActivatedDateUtc = new DateTime(2019, 3, 27, 9, 14, 36, 853, DateTimeKind.Utc), Birthday = new DateTime(1992, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatedDateUtc = new DateTime(2019, 4, 10, 9, 58, 48, 886, DateTimeKind.Utc), Email = "admin@google.com", EmailIsConfirmed = false, EmailIsSubscribe = false, FathersName = "Andreevich", IsActive = true, Login = "vektor", Name = "Viktor", Password = "cvgWVx2PzyodoHjQuvNZza7SQzZ/dN3lACijh7STvr0=", PhoneIsConfirmed = true, PhoneNumber = "7771291221", Salt = "RrL2RyNzrMzB6CA7ZRe+9g==", SurName = "Bochikalov" },
                        new { Id = 2, CreatedDateUtc = new DateTime(2019, 4, 10, 9, 58, 48, 888, DateTimeKind.Utc), EmailIsConfirmed = false, EmailIsSubscribe = false, IsActive = true, Name = "Levon", Password = "prMiHmsITfkH/siMY/aRmpP5epzS0tuKir39cp+dbtw=", PhoneIsConfirmed = false, PhoneNumber = "7771940504", Salt = "fqVPoSLeMzonCyoK0NbBUg==", SurName = "Kukuyan" }
                    );
                });

            modelBuilder.Entity("Entities.Models.ConfirmationKey", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("ConfirmationKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Token", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
